version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: leadnurturebot-db
    environment:
      POSTGRES_DB: leadnurturebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - leadnurturebot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: leadnurturebot-redis
    ports:
      - "6379:6379"
    networks:
      - leadnurturebot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leadnurturebot-backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/leadnurturebot
      - REDIS_URL=redis://redis:6379/0
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-https://api.whatsapp.com}
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN:-your-token}
      - WHATSAPP_PHONE_NUMBER=${WHATSAPP_PHONE_NUMBER:-+1234567890}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - leadnurturebot-network

  # Celery Worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leadnurturebot-celery
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/leadnurturebot
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    networks:
      - leadnurturebot-network

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leadnurturebot-celery-beat
    command: celery -A config beat -l info
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/leadnurturebot
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    networks:
      - leadnurturebot-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leadnurturebot-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    networks:
      - leadnurturebot-network

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: leadnurturebot-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - leadnurturebot-network

networks:
  leadnurturebot-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: